//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : FishingJoy
//  @ File Name : StaticData.cpp
//  @ Date : 2017/9/30
//  @ Author : Gloria 211506309
//
//


#include<iostream>
using namespace std;
#include "StaticData.h"	
#include "cocoas2d.h"						//头文件														
	
static StaticData * g_sharedStaticData = NULL ;	//定义一个静态全局指针变量

StaticData* StaticData::sharedStaticData() {

	if (g_sharedStaticData==NULL)				//若g_sharedStaticData为空
	{
		g_sharedStaticData=new StaticData;		//调用new StaticData的方法发放申请新对象并且
		_sharedStaticData->init();				//调用init的成员函数完成相关初始化操作
	}

	return _sharedStaticData;					//返回值_sharedStaticData
}

void StaticData::purge() {

	//当内存不足时调用释放g_sharedStaticData的内存
	CC_SAFE_RELEASE_NULL(g_sharedStaticData);
}

int StaticData::intValueForKey(const std::string &key) {

	//返回该项对应的整形值
	return _dictionary->valueForKey(key)-> intValue ();

}

const char* StaticData::stringValueFromKey(const std::string &key) {

	//返回_dictionary 中key对应的值类型得到字符串
	return _dictionary->valueForKey(key)->getCString();  

}

bool StaticData::booleanFromKey(const std::string &key) {

	//返回该项对应的布尔值
	return _dictionary->valueForKey(key)-> boolValue ();

}

cocos2d::CCPoint StaticData::pointFromKey(const std::string &key) {

	//返回该项对应的点
	return _dictionary->valueForKey(key)-> getCString ();

}

cocos2d::CCRect StaticData::rectFromKey(const std::string &key) {

	//返回字符串所对应的矩形
	return _dictionary->valueForKey(key)-> getCString ();

cocos2d::CCSize StaticData::sizeFromKey(const std::string &key) {
	//返回字符串所对应的范围
return _dictionary->valueForKey(key)-> getCString ();
}

bool StaticData::init() {
//初始化一个字典，数据的  
    _dictionary = CCDictionary::createWithContentsOfFile(_staticDataPath.plist);  
    //这个字典需要在当前这个类retain一下  
    CC_SAFE_RETAIN(_dictionary);  
    return true;  
}

StaticData::~StaticData() {

	//在析构函数中释放_dictionary内存

	CC_SAFE_RELEASE_NULL(_dictionary);
}

StaticData::StaticData() {

	//给数据成员_staticDataPath赋值

	StaticData static_data;
	_staticDataPath=static_data.plist;

}

